-------------------------------------------------------------------------------
Test set: wcs.cerebook.repository.UserRepositoryTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 14.118 s <<< FAILURE! - in wcs.cerebook.repository.UserRepositoryTest
save  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #1 of URL [file:/C:/Users/mabox/intelij/Cerebook/target/classes/data.sql]: INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021"); nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Colonne "NICKNAME" non trouvée
Column "NICKNAME" not found; SQL statement:
INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021") [42122-200]
Caused by: org.springframework.jdbc.datasource.init.ScriptStatementFailedException: 
Failed to execute SQL script statement #1 of URL [file:/C:/Users/mabox/intelij/Cerebook/target/classes/data.sql]: INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021"); nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Colonne "NICKNAME" non trouvée
Column "NICKNAME" not found; SQL statement:
INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021") [42122-200]
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: 
Colonne "NICKNAME" non trouvée
Column "NICKNAME" not found; SQL statement:
INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021") [42122-200]

essai  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #1 of URL [file:/C:/Users/mabox/intelij/Cerebook/target/classes/data.sql]: INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021"); nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Colonne "NICKNAME" non trouvée
Column "NICKNAME" not found; SQL statement:
INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021") [42122-200]
Caused by: org.springframework.jdbc.datasource.init.ScriptStatementFailedException: 
Failed to execute SQL script statement #1 of URL [file:/C:/Users/mabox/intelij/Cerebook/target/classes/data.sql]: INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021"); nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Colonne "NICKNAME" non trouvée
Column "NICKNAME" not found; SQL statement:
INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021") [42122-200]
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: 
Colonne "NICKNAME" non trouvée
Column "NICKNAME" not found; SQL statement:
INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021") [42122-200]

findByNickName  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #1 of URL [file:/C:/Users/mabox/intelij/Cerebook/target/classes/data.sql]: INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021"); nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Colonne "NICKNAME" non trouvée
Column "NICKNAME" not found; SQL statement:
INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021") [42122-200]
Caused by: org.springframework.jdbc.datasource.init.ScriptStatementFailedException: 
Failed to execute SQL script statement #1 of URL [file:/C:/Users/mabox/intelij/Cerebook/target/classes/data.sql]: INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021"); nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Colonne "NICKNAME" non trouvée
Column "NICKNAME" not found; SQL statement:
INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021") [42122-200]
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: 
Colonne "NICKNAME" non trouvée
Column "NICKNAME" not found; SQL statement:
INSERT INTO cerebook_user(id, nickName, firstName, lastName, city, address, email, password, birthday) VALUES (nextval ('hibernate_sequence'), 'Wolverine', Michel, Mipoivre, Tanbougtou, michelmipoivre, rrrr, dfdfdfdf, "11/3/2021") [42122-200]

